version: 0.0
os: linux
files:
  - source: frontend/build
    destination: /var/www/portfolio/frontend
  - source: backend
    destination: /var/www/portfolio/backend
  - source: scripts
    destination: /var/www/portfolio/scripts
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root