version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
      python: 3.12
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - node --version
      - python --version
      - echo Pre-build phase started on `date`
      - cd frontend && npm install
      - cd ../backend && pip install -r requirements.txt
      
  build:
    commands:
      - echo Build phase started on `date`
      - cd ../frontend
      - npm run build
      - echo Frontend build completed
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  name: portfolio-build-$(date +%Y-%m-%d)